# src/scrapers/selenium_wikipedia_population.py
"""
This module uses Selenium to scrape historical state population data from Wikipedia.
It demonstrates interacting with a page (e.g., waiting for elements) and
parsing a complex HTML table.
The Wikipedia page is not fully generated by JavaScript, but it does have some
JavaScript elements for sorting, that can be manipulated using selenium.
"""
import logging
from typing import List, Dict, Optional

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options as ChromeOptions
from webdriver_manager.chrome import ChromeDriverManager

logger = logging.getLogger(__name__)

class WikipediaPopulationScraper:
    """
    Scrapes historical US state population data from a Wikipedia table.
    URL: https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_historical_population
    """
    URL = "https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_historical_population"
    # We will target the first table, which contains the state data.
    TABLE_XPATH = '//*[@id="mw-content-text"]/div[1]/table[2]'

    def __init__(self, headless: bool = True):
        self.headless = headless
        self.driver = self._initialize_driver()

    def _initialize_driver(self) -> webdriver.Chrome:
        logger.info("Initializing Selenium WebDriver for Wikipedia...")
        options = ChromeOptions()
        if self.headless:
            options.add_argument("--headless")
        options.add_argument("--window-size=1920,1080")
        options.add_argument("--log-level=3")
        service = ChromeService(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=options)
        logger.info("WebDriver initialized.")
        return driver

    def _clean_population_string(self, pop_str: str) -> Optional[int]:
        """Removes commas and converts a population string to an integer."""
        if not pop_str or not isinstance(pop_str, str):
            return None
        try:
            return int(pop_str.replace(",", "").strip())
        except (ValueError, TypeError):
            return None

    def scrape(self, target_years: List[int]) -> Optional[List[Dict]]:
        """
        Navigates to the Wikipedia page and parses the historical population table.
        """
        try:
            logger.info(f"Navigating to {self.URL}...")
            self.driver.get(self.URL)
            self.driver.implicitly_wait(10)

            table = self.driver.find_element(By.XPATH, self.TABLE_XPATH)
            if not table:
                logger.error("Could not find the historical population table on Wikipedia.")
                return None

            logger.info("Found population table. Parsing headers and rows...")

            header_elements = table.find_elements(By.TAG_NAME, "th")
            headers = [th.text.strip() for th in header_elements]

            # Create a map of the year (as a string) to its column index
            year_to_index_map = {}
            for year in target_years:
                year_str = str(year)
                # Find the header that starts with the year string (e.g., "2020" or "2020[10]")
                for i, header in enumerate(headers):
                    if header.startswith(year_str):
                        year_to_index_map[year_str] = i
                        break

            if not year_to_index_map:
                logger.error(f"Could not map any target years {target_years} to table columns. Headers found: {headers}")
                return None

            logger.info(f"Mapped column indices for years: {year_to_index_map}")

            population_data = []
            # Select all `tr` elements within the `tbody`
            rows = table.find_elements(By.CSS_SELECTOR, "tbody tr")

            for row in rows[1:]: # Skip the first row which is part of the header
                # State name is in a <th> tag at the start of the row
                state_name_element = row.find_element(By.TAG_NAME, "th")
                state_name = state_name_element.text.strip()

                # All other data points are in <td> tags
                cols = row.find_elements(By.TAG_NAME, "td")

                for year_str, header_index in year_to_index_map.items():
                    # The column index for the 'td's will be one less than the
                    # header index, because the state name 'th' is not in the 'cols' list.
                    # The first data column (1790) corresponds to cols[0].
                    # The first header (Name) is at headers[0].
                    # So, the data for header[i] is at cols[i-1].
                    col_index = header_index - 1

                    if col_index < len(cols):
                        pop_str = cols[col_index].text
                        population = self._clean_population_string(pop_str)
                        if state_name and population:
                            population_data.append({
                                'state_name': state_name,
                                'year': int(year_str),
                                'population': population
                            })

            logger.info(f"Successfully scraped population data for {len(population_data)} state-year combinations.")
            return population_data

        except Exception as e:
            logger.error(f"An error occurred during Selenium scraping of Wikipedia: {e}", exc_info=True)
            return None
        finally:
            if self.driver:
                logger.info("Closing Selenium WebDriver.")
                self.driver.quit()